name: kerberos_client
description: "The Last Original - Zero-Trust Digital Provenance"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Local Ledger & Encryption
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Edge-native Vector Storage
  objectbox: ^2.4.0
  objectbox_flutter_libs: ^2.4.0
  
  # Networking & Signaling
  flutter_webrtc: ^1.6.1
  supabase_flutter: ^2.0.2
  
  # File Processing & Parsing
  syncfusion_flutter_pdf: ^24.1.41
  path_provider: ^2.1.2
  crypto: ^3.0.3
  uuid: ^4.3.3
  
  # UI constraints & Utils
  flutter_dotenv: ^5.1.0
  ffi: ^2.1.0
  desktop_drop: ^0.4.4
  file_picker: ^8.0.7
  google_fonts: ^8.2.1
  record: ^7.1.1
  audioplayers: ^6.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1
  objectbox_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - .env
