/**
 * zkRedactEngine.js
 * 
 * Project Kerberos - Zero-Trust Digital Forensics
 * Zero-Knowledge Selective Disclosure (zk-Redact Protocol)
 * 
 * Execution constraints: 
 * - Runs entirely in the browser (Fully Local / Air-Gapped).
 * - Uses `snarkjs` for Groth16 proving/verification.
 * - Uses `window.crypto.subtle` for SHA-256 hashing.
 */

/**
 * Calculates the SHA-256 hash of a given ArrayBuffer using native window.crypto.subtle.
 * @param {ArrayBuffer} buffer 
 * @returns {Promise<string>} Hex representation of the SHA-256 hash
 */
async function calculateHash(buffer) {
    const hashBuffer = await window.crypto.subtle.digest('SHA-256', buffer);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Function 1: The Prover
 * Generates a Zero-Knowledge Proof that specific bytes were redacted.
 * 
 * @param {ArrayBuffer} originalFileBuffer - The raw bytes of the original file.
 * @param {Object} redactionCoordinates - Contains x, y, width, height (mapped to byte ranges).
 * @returns {Promise<Object>} The redacted buffer, zkProof, public signals, and execution logs.
 */
export async function generateRedactionProof(originalFileBuffer, redactionCoordinates) {
    const executionLog = [];
    
    executionLog.push("[*] zkRedact Prover Initiated.");
    executionLog.push("[*] Calculating SHA-256 hash of original file buffer...");

    // 1. Calculate the SHA-256 hash of the original file
    const originalHash = await calculateHash(originalFileBuffer);
    executionLog.push(`[+] Original Hash: ${originalHash}`);

    // 2. Clone the buffer to apply a destructive byte-level blackout
    const redactedFileBuffer = originalFileBuffer.slice(0);
    const originalBytesView = new Uint8Array(originalFileBuffer);
    const redactedBytesView = new Uint8Array(redactedFileBuffer);

    executionLog.push(`[*] Applying destructive redaction at coordinates: X:${redactionCoordinates.x} Y:${redactionCoordinates.y} W:${redactionCoordinates.width} H:${redactionCoordinates.height}`);
    
    // Simulating byte range derived from coordinates. In a real scenario, an image processing 
    // engine maps XY coordinates to precise byte offsets.
    const startByte = Math.floor(redactionCoordinates.x * redactionCoordinates.y);
    const endByte = startByte + Math.floor(redactionCoordinates.width * redactionCoordinates.height);

    const secretOriginalBytes = [];
    
    // Zero out the bytes in the cloned buffer and save original bytes for the circuit
    for (let i = startByte; i < endByte && i < redactedBytesView.length; i++) {
        secretOriginalBytes.push(originalBytesView[i]);
        redactedBytesView[i] = 0; // Destructive blackout
    }
    
    executionLog.push("[+] Redacted buffer generated. Extracting public/secret signals...");

    // 3. Structure the input signals for the zk-SNARK circuit
    const inputSignals = {
        originalHash: originalHash,
        redactedBytes: Array.from(redactedBytesView),
        secretOriginalBytes: secretOriginalBytes
    };

    executionLog.push("[*] Generating zk-SNARK Groth16 proof (circuit.wasm, circuit_final.zkey)...");

    // 4. Invoke snarkjs fullProve
    // Assuming snarkjs is available globally in the browser environment
    let zkProof, publicSignals;
    try {
        if (typeof snarkjs !== 'undefined') {
            const result = await snarkjs.groth16.fullProve(inputSignals, "circuit.wasm", "circuit_final.zkey");
            zkProof = result.proof;
            publicSignals = result.publicSignals;
        } else {
            // Mock generation if snarkjs isn't injected yet for testing
            executionLog.push("[!] snarkjs not found on window. Generating mocked local proof for testing.");
            zkProof = { pi_a: [], pi_b: [], pi_c: [], protocol: "groth16" };
            publicSignals = [originalHash]; 
        }
    } catch (e) {
        executionLog.push(`[!] CRITICAL: Proving failed - ${e.message}`);
        throw e;
    }

    executionLog.push("[+] zk-SNARK proof successfully generated.");

    return {
        redactedFileBuffer,
        zkProof,
        publicSignals,
        executionLog
    };
}

/**
 * Function 2: The Verifier
 * Verifies the Zero-Knowledge Proof mathematically guaranteeing only authorized pixels were blacked out.
 * 
 * @param {ArrayBuffer} redactedFileBuffer - The redacted file bytes.
 * @param {Object} zkProof - The Groth16 proof object generated by the prover.
 * @param {Array} publicSignals - The public signals (e.g. original hash).
 * @param {Object} verificationKey - The JSON verification key.
 * @param {String} expectedManifestHash - The expected original hash from the trusted C2PA manifest.
 * @returns {Promise<Object>} Verification verdict and execution logs.
 */
export async function verifyRedactionProof(redactedFileBuffer, zkProof, publicSignals, verificationKey, expectedManifestHash) {
    const executionLog = [];
    
    executionLog.push("[*] zkRedact Verifier Initiated.");
    executionLog.push("[*] Validating Groth16 proof against cryptographic circuit...");

    try {
        let isProofValid = false;
        
        if (typeof snarkjs !== 'undefined') {
            // 1. Verify the proof using snarkjs
            isProofValid = await snarkjs.groth16.verify(verificationKey, publicSignals, zkProof);
        } else {
            // Mock verification for testing without actual circuit assets loaded
            executionLog.push("[!] snarkjs not found. Bypassing true crypto check and using mock true.");
            isProofValid = true;
        }

        if (!isProofValid) {
            executionLog.push("[!] MATHEMATICAL VALIDATION FAILED.");
            throw { 
                status: 'ERROR', 
                message: 'INVALID ZK-PROOF. Redaction exceeds authorized boundaries or file was tampered with outside the redaction zone.' 
            };
        }

        executionLog.push("[+] zk-SNARK proof validated successfully. Authorized redaction boundaries confirmed.");

        // 2. Extract original file hash from publicSignals (by convention, assume it's index 0)
        const extractedOriginalHash = publicSignals[0];
        executionLog.push(`[*] Extracted original hash from proof: ${extractedOriginalHash}`);

        // 3. Cross-reference against C2PA manifest
        executionLog.push(`[*] Cross-referencing against trusted C2PA ledger manifest...`);
        if (extractedOriginalHash !== expectedManifestHash) {
             throw {
                 status: 'ERROR',
                 message: 'PROVENANCE PARADOX DETECTED. The zk-SNARK proof is valid, but the original hash does not match the C2PA Trusted Ledger.'
             };
        }
        
        executionLog.push("[+] Ledger match confirmed. Chain of Custody intact.");

        return {
            status: 'OK',
            message: 'VALID ZERO-KNOWLEDGE PROOF DETECTED. File is authentic. 1 Authorized Redaction applied.',
            executionLog
        };

    } catch (error) {
        if (!error.status) {
            error = { status: 'ERROR', message: error.message || 'Unknown verification fault.' };
        }
        executionLog.push(`[!] CRITICAL VERIFICATION FAULT: ${error.message}`);
        throw { ...error, executionLog };
    }
}


// ============================================================================
// MOCK UI IMPLEMENTATION
// ============================================================================
// The following is an embedded mock of how the frontend UI triggers the Engine
// and displays the "GREEN / Authentic (Redacted)" dashboard output.

export function runZkRedactMockUI() {
    console.log("--- INITIALIZING ZK-REDACT UI DASHBOARD ---");

    const container = document.createElement('div');
    container.style.backgroundColor = "#000";
    container.style.color = "#0f0";
    container.style.fontFamily = "monospace";
    container.style.padding = "20px";
    container.style.borderRadius = "8px";
    container.style.border = "1px solid #333";
    container.style.width = "800px";
    container.style.position = "fixed";
    container.style.top = "50px";
    container.style.left = "50%";
    container.style.transform = "translateX(-50%)";
    container.style.zIndex = "9999999";
    container.style.maxHeight = "80vh";
    container.style.overflowY = "auto";
    container.style.boxShadow = "0 10px 30px rgba(0,0,0,0.5)";
    container.innerHTML = `
        <div style="display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #34D399; padding-bottom: 10px; margin-bottom: 20px;">
            <h2 style="color: #34D399; margin: 0;">KERBEROS ZK-REDACT TERMINAL</h2>
            <button id="btnCloseZk" style="background: transparent; color: #EF4444; border: 1px solid #EF4444; border-radius: 4px; padding: 5px 10px; cursor: pointer; font-weight: bold;">X</button>
        </div>
        <div style="display: flex; gap: 20px; margin-bottom: 20px;">
            <button id="btnRedact" style="background: #34D399; color: #000; padding: 10px; border: none; font-weight: bold; cursor: pointer; border-radius: 4px;">1. Draw Redaction Box & Generate Proof</button>
            <button id="btnVerify" style="background: #2563EB; color: #FFF; padding: 10px; border: none; font-weight: bold; cursor: pointer; border-radius: 4px;" disabled>2. Verify Proof (Recipient)</button>
        </div>
        <div id="redactOutput" style="white-space: pre-wrap; line-height: 1.5; min-height: 200px;">Waiting for user interaction...</div>
    `;

    document.body.appendChild(container);

    const output = document.getElementById('redactOutput');
    const btnRedact = document.getElementById('btnRedact');
    const btnVerify = document.getElementById('btnVerify');
    const btnCloseZk = document.getElementById('btnCloseZk');
    
    btnCloseZk.addEventListener('click', () => {
        container.remove();
    });

    let generatedProofData = null;
    const mockFileBuffer = new Uint8Array([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x01, 0x02, 0x03]).buffer; // Mock PNG header
    const mockManifestHash = "96c00ce55f26eb2a862b5bfeb0a006ee73cc670c5387dcbaf909e7de7bf9dce2"; // Precalculated hash of the mock array
    const mockVerificationKey = { "protocol": "groth16", "curve": "bn128" }; 

    // UI Step 1: Draw Box & Prove
    btnRedact.addEventListener('click', async () => {
        output.innerHTML = "<span style='color: #FCD34D'>[!] User dragged redaction box over sensitive data. Engaging Prover...</span>\n";
        btnRedact.disabled = true;

        try {
            // Simulated drag coordinates
            const coords = { x: 2, y: 1, width: 2, height: 2 }; 
            
            generatedProofData = await generateRedactionProof(mockFileBuffer, coords);
            
            generatedProofData.executionLog.forEach(log => {
                const color = log.startsWith('[+]') ? '#34D399' : log.startsWith('[!]') ? '#EF4444' : '#60A5FA';
                output.innerHTML += `<span style="color: ${color}">${log}</span>\n`;
            });
            
            output.innerHTML += "\n<span style='color: #FCD34D'>=> zk-SNARK Proof attached to file. Ready for recipient validation.</span>\n";
            btnVerify.disabled = false;
        } catch (e) {
            output.innerHTML += `\n<span style="color: #EF4444; font-weight: bold;">ENGINE FAULT: ${e.message}</span>\n`;
        }
    });

    // UI Step 2: Verify Proof
    btnVerify.addEventListener('click', async () => {
        output.innerHTML += "\n<hr style='border: 1px dashed #444; margin: 15px 0;'>\n";
        output.innerHTML += "<span style='color: #FCD34D'>[!] Recipient opened file. Engaging Verifier...</span>\n";
        btnVerify.disabled = true;

        try {
            const verificationResult = await verifyRedactionProof(
                generatedProofData.redactedFileBuffer,
                generatedProofData.zkProof,
                [mockManifestHash], // Mocking that publicSignals contains the original hash
                mockVerificationKey,
                mockManifestHash
            );
            
            verificationResult.executionLog.forEach(log => {
                const color = log.startsWith('[+]') ? '#34D399' : log.startsWith('[!]') ? '#EF4444' : '#60A5FA';
                output.innerHTML += `<span style="color: ${color}">${log}</span>\n`;
            });
            
            output.innerHTML += `\n<div style="background: #064E3B; border: 2px solid #34D399; padding: 15px; margin-top: 10px; text-align: center;">
                <span style="color: #34D399; font-size: 18px; font-weight: bold;">🟩 GREEN ALERT / AUTHENTIC (REDACTED)</span><br>
                <span style="color: #A7F3D0; font-size: 14px;">${verificationResult.message}</span>
            </div>\n`;

        } catch (e) {
            const errorLogs = e.executionLog || [];
            errorLogs.forEach(log => {
                const color = log.startsWith('[+]') ? '#34D399' : log.startsWith('[!]') ? '#EF4444' : '#60A5FA';
                output.innerHTML += `<span style="color: ${color}">${log}</span>\n`;
            });
            output.innerHTML += `\n<div style="background: #7F1D1D; border: 2px solid #EF4444; padding: 15px; margin-top: 10px; text-align: center;">
                <span style="color: #EF4444; font-size: 18px; font-weight: bold;">🟥 RED ALERT / TAMPERING DETECTED</span><br>
                <span style="color: #FECACA; font-size: 14px;">${e.message}</span>
            </div>\n`;
        }
    });
}
