import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:http/http.dart' as http;

/// Structured result returned from Gemini 2.5 Flash neural evaluation.
class GeminiForensicResult {
  final bool isSuccess;
  final double syntheticProbability; // 0.00 to 1.00
  final String modelLineage;
  final String executiveSummary;
  final List<String> forensicIndicators;
  final List<Map<String, dynamic>> sentenceEvaluations;
  final String euAiActCompliance;
  final String usEo14110Compliance;
  final String? errorMessage;

  const GeminiForensicResult({
    required this.isSuccess,
    this.syntheticProbability = 0.0,
    this.modelLineage = 'Unknown',
    this.executiveSummary = '',
    this.forensicIndicators = const [],
    this.sentenceEvaluations = const [],
    this.euAiActCompliance = 'UNKNOWN',
    this.usEo14110Compliance = 'UNKNOWN',
    this.errorMessage,
  });

  factory GeminiForensicResult.error(String message) {
    return GeminiForensicResult(
      isSuccess: false,
      errorMessage: message,
    );
  }
}

/// Client for Google Gemini 2.5 Flash enterprise multimodal forensic inspection.
class GeminiAiClient {
  static const String defaultModel = 'gemini-2.5-flash-lite';
  static const String apiBase =
      'https://generativelanguage.googleapis.com/v1beta/models';

  static String? _inMemoryApiKey;

  /// Sets or updates the in-memory API key (persists during the active session).
  static void setApiKey(String key) {
    _inMemoryApiKey = key.trim();
  }

  /// Resolves the API key: either an explicitly passed key, from in-memory cache, or from .env
  static String? getApiKey({String? overrideKey}) {
    if (overrideKey != null && overrideKey.trim().isNotEmpty) {
      return overrideKey.trim();
    }
    if (_inMemoryApiKey != null && _inMemoryApiKey!.isNotEmpty) {
      return _inMemoryApiKey;
    }
    try {
      final envKey = dotenv.env['GEMINI_API_KEY'];
      if (envKey != null && envKey.trim().isNotEmpty) {
        return envKey.trim();
      }
    } catch (_) {}

    // Support compile-time dart-define injection from Vercel / CI
    const dartDefineKey = String.fromEnvironment('GEMINI_API_KEY');
    if (dartDefineKey.isNotEmpty) {
      return dartDefineKey.trim();
    }

    return null;
  }

  static const String vercelEndpoint =
      'https://kerberos-obsidian.vercel.app/api/gemini-key';
  static bool _isFetchingFromVercel = false;

  /// Dynamically fetches the GEMINI_API_KEY from Vercel environment variables.
  /// Eliminates the need to ever store the API key in local .env files.
  static Future<String?> fetchKeyFromVercel() async {
    if (_inMemoryApiKey != null && _inMemoryApiKey!.isNotEmpty) {
      return _inMemoryApiKey;
    }
    if (_isFetchingFromVercel) return null;
    _isFetchingFromVercel = true;

    try {
      final uri = Uri.parse(vercelEndpoint);
      final response = await http.get(uri).timeout(const Duration(seconds: 8));
      final contentType = response.headers['content-type'] ?? '';
      if (response.statusCode == 200 && contentType.contains('json')) {
        final data = jsonDecode(response.body) as Map<String, dynamic>;
        final key = data['apiKey'] as String?;
        if (key != null && key.trim().isNotEmpty) {
          _inMemoryApiKey = key.trim();
          debugPrint(
              '[GeminiAiClient] Successfully dynamically fetched GEMINI_API_KEY from Vercel!');
          return _inMemoryApiKey;
        }
      }
    } catch (e) {
      debugPrint('[GeminiAiClient] Dynamic Vercel key fetch notice: $e');
    } finally {
      _isFetchingFromVercel = false;
    }
    return null;
  }

  /// Ensures an API key is available, attempting dynamic Vercel fetch if not present locally.
  static Future<String?> ensureApiKey({String? overrideKey}) async {
    final existing = getApiKey(overrideKey: overrideKey);
    if (existing != null && existing.isNotEmpty) {
      return existing;
    }
    return await fetchKeyFromVercel();
  }

  /// Evaluates document text or raw text extracts with Gemini 2.5 Flash.
  static Future<GeminiForensicResult> evaluateText({
    required String text,
    String? overrideApiKey,
    String model = defaultModel,
  }) async {
    final apiKey = await ensureApiKey(overrideKey: overrideApiKey);
    if (apiKey == null) {
      return GeminiForensicResult.error(
          'GEMINI_API_KEY is not configured in Vercel or settings');
    }

    final prompt = '''
You are a rigorous Enterprise AI Content Forensic Auditor calibrated to Turnitin and GPTZero industry detection benchmarks.
Analyze the following document text to determine whether it was generated by an AI (e.g. GPT-4, Claude 3.5, Gemini, Llama) or written by a human.

CALIBRATION RULES (MANDATORY):
1. SHORT / CASUAL / PERSONAL TEXT MUST BE CLASSIFIED AS HUMAN:
   - If the text is short (< 35 words), informal, conversational, personal, or fragmented (e.g. "i love zoro", casual notes, stream-of-consciousness, personal opinions, lowercase chatter), synthetic_probability MUST be between 0.01 and 0.05. Model lineage MUST be "Authentic Human Expression". NEVER classify short, personal statements as AI.
2. AI-GENERATED CHARACTERISTICS:
   - AI generation is characterized by:
     * Unusually low perplexity: High predictability of every subsequent word, uniform clause lengths.
     * Absence of personal idiosyncrasies, authentic anecdotes, or emotional texture.
     * Symmetrical argumentative structure (e.g., "Firstly... Secondly... Furthermore... In conclusion...").
     * Generic explanatory tone that states facts without genuine lived perspective.
     * High density of abstract nouns and passive/participial phrases.
   - If the text displays these structural AI patterns even without obvious buzzwords, assign synthetic_probability between 0.85 and 0.99.
3. HUMAN WRITING CHARACTERISTICS:
   - Variable burstiness (mix of very short sentences with long rambling ones), personal pronouns, casual diction, genuine specific details, colloquial phrasing, typos or irregular rhythm. Assign synthetic_probability < 0.20.

Document Text:
"""
$text
"""

Output strictly valid JSON with no enclosing markdown fences matching this schema:
{
  "synthetic_probability": 0.05,
  "model_lineage": "Authentic Human Expression or specific AI model",
  "executive_summary": "Detailed forensic explanation of why this text is human or AI.",
  "forensic_indicators": [
    "Indicator 1",
    "Indicator 2"
  ],
  "sentence_evaluations": [
    {
      "sentence_index": 1,
      "text": "sentence text",
      "ai_probability": 0.05,
      "reason": "explanation of sentence attribution"
    }
  ],
  "regulatory_compliance": {
    "eu_ai_act_article_52": "HUMAN_AUTHORED or NON_COMPLIANT_UNTAGGED_SYNTHETIC",
    "us_eo_14110_watermarking": "NOT_APPLICABLE or MISSING_SYNTHETIC_MARKINGS"
  }
}
''';

    return _postToGemini(
      apiKey: apiKey,
      model: model,
      contents: [
        {
          'role': 'user',
          'parts': [
            {'text': prompt}
          ]
        }
      ],
    );
  }

  /// Evaluates an image or video keyframe with Gemini 2.5 Flash multimodal vision.
  static Future<GeminiForensicResult> evaluateVisualMedia({
    required Uint8List imageBytes,
    required String mimeType,
    String? overrideApiKey,
    String model = defaultModel,
    String? contextMetadata,
  }) async {
    final apiKey = await ensureApiKey(overrideKey: overrideApiKey);
    if (apiKey == null) {
      return GeminiForensicResult.error(
          'GEMINI_API_KEY is not configured in Vercel or settings');
    }

    final base64Image = base64Encode(imageBytes);
    final prompt = '''
You are the Kerberos Enterprise Forensic Visual Inspector & Deepfake Detector.
Analyze this image file for synthetic AI generation (Midjourney, Stable Diffusion, DALL-E, Firefly, Flux.1) or deepfake facial/spatial manipulation.
Inspect:
1. Micro-texture consistency, sensor noise floor (PRNU absence), unnatural skin smoothing, anomalous high-frequency grids.
2. Anatomical inconsistencies (eyes, corneal reflections, fingers, earrings, text glyph hallucinations).
3. Background depth-of-field warping and lighting coherence.
Additional Metadata context: ${contextMetadata ?? 'None'}

Output strictly valid JSON with no markdown fences and no extra text matching this exact schema:
{
  "synthetic_probability": 0.92,
  "model_lineage": "Midjourney v6 / Stable Diffusion XL Architecture",
  "executive_summary": "Sub-pixel diffusion textures and absence of camera sensor PRNU noise floor.",
  "forensic_indicators": [
    "Corneal reflection divergence in left pupil",
    "High-frequency deconvolution checkerboard artifacts",
    "Unnatural background depth-of-field boundary falloff"
  ],
  "sentence_evaluations": [],
  "regulatory_compliance": {
    "eu_ai_act_article_52": "NON_COMPLIANT_UNTAGGED_SYNTHETIC",
    "us_eo_14110_watermarking": "MISSING_C2PA_MANIFEST"
  }
}
''';

    return _postToGemini(
      apiKey: apiKey,
      model: model,
      contents: [
        {
          'role': 'user',
          'parts': [
            {'text': prompt},
            {
              'inline_data': {
                'mime_type': mimeType,
                'data': base64Image,
              }
            }
          ]
        }
      ],
    );
  }

  /// Core HTTP POST dispatcher to Gemini Generative Language API
  static Future<GeminiForensicResult> _postToGemini({
    required String apiKey,
    required String model,
    required List<Map<String, dynamic>> contents,
  }) async {
    final modelsToTry = [
      model,
      if (model != 'gemini-2.5-flash-lite') 'gemini-2.5-flash-lite',
      if (model != 'gemini-3.6-flash') 'gemini-3.6-flash',
      'gemini-flash-latest',
    ];

    String lastError = 'No models available';

    for (final currentModel in modelsToTry) {
      try {
        final uri = Uri.parse('$apiBase/$currentModel:generateContent?key=$apiKey');
        final bodyPayload = jsonEncode({
          'contents': contents,
          'generationConfig': {
            'temperature': 0.1,
            'maxOutputTokens': 2048,
            'responseMimeType': 'application/json',
          }
        });

        final response = await http.post(
          uri,
          headers: {'Content-Type': 'application/json'},
          body: bodyPayload,
        ).timeout(const Duration(seconds: 20));

        final responseBody = response.body;

        if (response.statusCode != 200) {
          debugPrint(
              '[GeminiAiClient] $currentModel HTTP ${response.statusCode}: $responseBody');
          lastError =
              'Gemini API error ($currentModel HTTP ${response.statusCode}): $responseBody';
          continue; // Try next fallback model
        }

        final parsed = jsonDecode(responseBody) as Map<String, dynamic>;
        final candidates = parsed['candidates'] as List?;
        if (candidates == null || candidates.isEmpty) {
          lastError = 'No generation candidates returned from $currentModel';
          continue;
        }

        final content = candidates[0]['content'] as Map<String, dynamic>?;
        final parts = content?['parts'] as List?;
        if (parts == null || parts.isEmpty) {
          lastError = 'Empty response content from $currentModel';
          continue;
        }

        String rawText = '';
        for (final part in parts) {
          final t = part['text'] as String?;
          if (t != null && t.trim().isNotEmpty) {
            rawText = t;
            break;
          }
        }
        rawText = rawText.trim();
        if (rawText.startsWith('```json')) {
          rawText = rawText.substring(7);
        } else if (rawText.startsWith('```')) {
          rawText = rawText.substring(3);
        }
        if (rawText.endsWith('```')) {
          rawText = rawText.substring(0, rawText.length - 3);
        }
        rawText = rawText.trim();

        final jsonResult = jsonDecode(rawText) as Map<String, dynamic>;

        final double synthProb =
            (jsonResult['synthetic_probability'] as num?)?.toDouble() ?? 0.0;
        final String modelLineage =
            jsonResult['model_lineage'] as String? ?? 'Unknown Model';
        final String summary = jsonResult['executive_summary'] as String? ??
            'Analysis completed successfully.';
        final List<String> indicators =
            (jsonResult['forensic_indicators'] as List?)
                    ?.map((e) => e.toString())
                    .toList() ??
                [];

        final List<Map<String, dynamic>> sentences =
            (jsonResult['sentence_evaluations'] as List?)
                    ?.map((e) => Map<String, dynamic>.from(e as Map))
                    .toList() ??
                [];

        final reg = jsonResult['regulatory_compliance'] as Map<String, dynamic>?;
        final String euReg =
            reg?['eu_ai_act_article_52'] as String? ?? 'UNKNOWN';
        final String usReg =
            reg?['us_eo_14110_watermarking'] as String? ?? 'UNKNOWN';

        return GeminiForensicResult(
          isSuccess: true,
          syntheticProbability: synthProb.clamp(0.0, 1.0),
          modelLineage: modelLineage,
          executiveSummary: summary,
          forensicIndicators: indicators,
          sentenceEvaluations: sentences,
          euAiActCompliance: euReg,
          usEo14110Compliance: usReg,
        );
      } catch (e, stack) {
        debugPrint('[GeminiAiClient] Exception on $currentModel: $e\n$stack');
        lastError = 'Gemini connection failed on $currentModel: $e';
      }
    }

    return GeminiForensicResult.error(lastError);
  }
}
