import 'dart:async';
import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/provenance_record.dart';

/// Zero-Trust local ledger.
/// Operates locally using AES-256 encryption via HiveCipher.
/// Provides seamless cross-computer cloud synchronization bound to the authenticated email.
class LedgerService extends ChangeNotifier {
  static const String _boxName = 'secure_provenance_ledger';
  late Box<ProvenanceRecord> _box;
  SupabaseClient? _supabase;

  LedgerService({SupabaseClient? supabaseClient}) : _supabase = supabaseClient;

  void setSupabaseClient(SupabaseClient client) {
    _supabase = client;
  }

  /// Initializes the air-gapped AES-256 encrypted ledger.
  /// Purges any legacy sample/mock assets to ensure an authentic clean state.
  Future<void> initialize() async {
    await Hive.initFlutter();
    
    // Register adapter generated by hive_generator
    if (!Hive.isAdapterRegistered(0)) {
      Hive.registerAdapter(ProvenanceRecordAdapter());
    }

    // Retrieve AES-256 key from secure environment variable layer
    final base64Key = dotenv.env['HIVE_ENCRYPTION_KEY_BASE64'];
    if (base64Key == null || base64Key.isEmpty) {
      throw Exception("Zero-Trust Fault: Ledger encryption key not found. System halting to protect data.");
    }

    final encryptionKey = base64Decode(base64Key);
    if (encryptionKey.length != 32) {
      throw Exception("Zero-Trust Fault: Invalid AES-256 key length detected.");
    }

    // Initialize exclusively with the strict AES-256 cipher
    _box = await Hive.openBox<ProvenanceRecord>(
      _boxName,
      encryptionCipher: HiveAesCipher(encryptionKey),
    );

    // PURGE SAMPLE ASSETS: Ensure demo/sample assets are never retained in persistent storage
    final sampleKeys = _box.keys.where((k) {
      final rec = _box.get(k);
      return k == 'sample-satellite-01' ||
          rec?.id == 'sample-satellite-01' ||
          rec?.filePath == 'satellite_recon_delta_09.png';
    }).toList();

    for (final k in sampleKeys) {
      await _box.delete(k);
    }
  }

  /// Appends a new cryptographically sealed record into the ledger and triggers cloud sync.
  Future<void> addRecord(ProvenanceRecord record) async {
    if (!_box.isOpen) {
      throw Exception("Zero-Trust Fault: Unauthorized attempted write to closed ledger.");
    }

    final currentEmail = _supabase?.auth.currentUser?.email;
    final recordToSave = (record.ownerEmail == null && currentEmail != null && currentEmail.isNotEmpty)
        ? record.copyWith(ownerEmail: currentEmail)
        : record;

    await _box.put(recordToSave.id, recordToSave);
    notifyListeners();

    // Asynchronously synchronize with authenticated user's cloud account
    if (currentEmail != null && currentEmail.isNotEmpty && _supabase != null) {
      unawaited(_syncLocalRecordsToCloud(currentEmail));
    }
  }

  /// Retrieves a provenance record by its UUID.
  ProvenanceRecord? getRecord(String id) {
    if (!_box.isOpen) {
      throw Exception("Zero-Trust Fault: Unauthorized attempted read from closed ledger.");
    }
    return _box.get(id);
  }

  /// Retrieves all sealed records in the ledger, excluding sample assets.
  /// Optionally filters by user email so records are cleanly partitioned per account.
  List<ProvenanceRecord> getHistory({String? filterEmail}) {
    if (!_box.isOpen) return [];

    final targetEmail = (filterEmail ?? _supabase?.auth.currentUser?.email)?.trim().toLowerCase();

    final records = _box.values.where((r) {
      // Never display sample or demo assets in the ledger
      if (r.id == 'sample-satellite-01' || r.filePath == 'satellite_recon_delta_09.png') {
        return false;
      }

      if (targetEmail != null && targetEmail.isNotEmpty) {
        final recordOwner = r.ownerEmail?.trim().toLowerCase();
        // Return records owned by this email, or legacy unassigned records
        return recordOwner == null || recordOwner == targetEmail;
      }

      return true;
    }).toList();

    return records.reversed.toList();
  }

  /// Retrieves the most recently sealed asset for quick P2P transfer.
  ProvenanceRecord? getLatestRecord({String? filterEmail}) {
    final history = getHistory(filterEmail: filterEmail);
    if (history.isEmpty) return null;
    return history.first;
  }

  /// Synchronizes ledger records between local Hive storage and Supabase user metadata.
  /// When a user logs in on Computer 2 with their email, this populates Computer 2's ledger
  /// with the files sealed previously on Computer 1.
  Future<void> syncWithUserAccount(User user) async {
    if (!_box.isOpen) return;
    final userEmail = user.email?.trim().toLowerCase();
    if (userEmail == null || userEmail.isEmpty) return;

    bool localModified = false;

    // 1. Pull sealed records stored in user metadata
    final meta = user.userMetadata;
    final remoteRaw = meta?['sealed_ledger_records'];
    final Set<String> knownIds = {};

    if (remoteRaw is List) {
      for (final item in remoteRaw) {
        if (item is Map) {
          try {
            final record = ProvenanceRecord.fromJson(Map<String, dynamic>.from(item));
            if (record.id.isNotEmpty && record.id != 'sample-satellite-01' && record.filePath != 'satellite_recon_delta_09.png') {
              knownIds.add(record.id);
              final existing = _box.get(record.id);
              if (existing == null) {
                await _box.put(record.id, record);
                localModified = true;
              } else if (existing.ownerEmail == null && record.ownerEmail != null) {
                await _box.put(record.id, existing.copyWith(ownerEmail: record.ownerEmail));
                localModified = true;
              }
            }
          } catch (e) {
            print(">> [LedgerService] Notice: Error restoring remote record: $e");
          }
        }
      }
    }

    // 2. Check for local records owned by this user (or unowned) that are not yet in cloud
    bool hasNewLocalForCloud = false;
    final localRecords = _box.values.where((r) {
      return r.id != 'sample-satellite-01' && r.filePath != 'satellite_recon_delta_09.png';
    }).toList();

    for (final r in localRecords) {
      final owner = r.ownerEmail?.trim().toLowerCase();
      if (owner == null) {
        // Tag unassigned local records with the active user email
        final updated = r.copyWith(ownerEmail: userEmail);
        await _box.put(r.id, updated);
        hasNewLocalForCloud = true;
        localModified = true;
      } else if (owner == userEmail && !knownIds.contains(r.id)) {
        hasNewLocalForCloud = true;
      }
    }

    // 3. If local storage had records not yet recorded in the cloud, push reconciled list
    if (hasNewLocalForCloud && _supabase != null) {
      await _syncLocalRecordsToCloud(userEmail);
    }

    if (localModified) {
      notifyListeners();
    }
  }

  /// Uploads the current user's sealed records to their Supabase account metadata.
  Future<void> _syncLocalRecordsToCloud(String email) async {
    if (_supabase == null || !_box.isOpen) return;
    final cleanEmail = email.trim().toLowerCase();
    if (cleanEmail.isEmpty) return;

    try {
      final userRecords = _box.values.where((r) {
        if (r.id == 'sample-satellite-01' || r.filePath == 'satellite_recon_delta_09.png') return false;
        final owner = r.ownerEmail?.trim().toLowerCase();
        return owner == null || owner == cleanEmail;
      }).toList();

      final recordsJson = userRecords.map((r) => r.copyWith(ownerEmail: cleanEmail).toJson()).toList();

      await _supabase!.auth.updateUser(
        UserAttributes(data: {'sealed_ledger_records': recordsJson}),
      );
      print(">> [LedgerService] Cloud sync successful: ${recordsJson.length} sealed records bound to $cleanEmail");
    } catch (e) {
      print(">> [LedgerService] Cloud sync notice (offline or transient): $e");
    }
  }

  /// Explicitly locks down the ledger, flushing all memory buffers.
  Future<void> lock() async {
    if (_box.isOpen) {
      await _box.close();
    }
  }
}

