import 'dart:async';
import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:uuid/uuid.dart';
import '../models/provenance_record.dart';

/// Zero-Trust local ledger.
/// Operates locally using AES-256 encryption via HiveCipher.
/// Provides seamless cross-computer cloud synchronization bound to the authenticated email.
class LedgerService extends ChangeNotifier {
  static const String _boxName = 'secure_provenance_ledger';
  late Box<ProvenanceRecord> _box;
  SupabaseClient? _supabase;

  // Distributed tombstone & sync state
  final Set<String> _deletedHashes = {};
  DateTime? _ledgerClearedAt;
  RealtimeChannel? _realtimeSyncChannel;
  Completer<void> _realtimeSubCompleter = Completer<void>();
  String? _currentSubscribedEmail;
  final String _localDeviceId = const Uuid().v4();

  LedgerService({SupabaseClient? supabaseClient}) : _supabase = supabaseClient;

  void setSupabaseClient(SupabaseClient client) {
    _supabase = client;
  }

  /// Initializes the air-gapped AES-256 encrypted ledger.
  /// Purges any legacy sample/mock assets to ensure an authentic clean state.
  Future<void> initialize() async {
    await Hive.initFlutter();
    
    // Register adapter generated by hive_generator
    if (!Hive.isAdapterRegistered(0)) {
      Hive.registerAdapter(ProvenanceRecordAdapter());
    }

    // Retrieve AES-256 key from secure environment variable layer
    final base64Key = dotenv.env['HIVE_ENCRYPTION_KEY_BASE64'];
    if (base64Key == null || base64Key.isEmpty) {
      throw Exception("Zero-Trust Fault: Ledger encryption key not found. System halting to protect data.");
    }

    final encryptionKey = base64Decode(base64Key);
    if (encryptionKey.length != 32) {
      throw Exception("Zero-Trust Fault: Invalid AES-256 key length detected.");
    }

    // Initialize exclusively with the strict AES-256 cipher
    _box = await Hive.openBox<ProvenanceRecord>(
      _boxName,
      encryptionCipher: HiveAesCipher(encryptionKey),
    );

    // ZERO-TRUST PURGE: Clear the current ledger state/mock data to remove 
    // any ingested .m4a files and legacy cloud-synced test data.
    await _box.clear();

    // PURGE SAMPLE ASSETS: Ensure demo/sample assets are never retained in persistent storage
    final sampleKeys = _box.keys.where((k) {
      final rec = _box.get(k);
      if (k == 'sample-satellite-01' ||
          rec?.id == 'sample-satellite-01' ||
          rec?.filePath == 'satellite_recon_delta_09.png') {
        return true;
      }
      // Zero-Trust Guard: Strictly reject and purge any audio mock data (prevent voice-spoofing)
      if (rec?.filePath.toLowerCase().endsWith('.m4a') == true) {
        return true;
      }
      return false;
    }).toList();

    for (final k in sampleKeys) {
      await _box.delete(k);
    }

    // DEDUPLICATE RECORDS: Purge any legacy duplicate records with identical hash & owner
    final Map<String, String> seenHashToKey = {};
    final List<dynamic> duplicateKeysToDelete = [];

    for (final key in _box.keys) {
      final rec = _box.get(key);
      if (rec == null) continue;
      if (rec.id == 'sample-satellite-01' || rec.filePath == 'satellite_recon_delta_09.png') continue;

      final hash = rec.originalFileHash.trim().toLowerCase();
      final owner = rec.ownerEmail?.trim().toLowerCase() ?? '';
      final compositeKey = '$owner::$hash';

      if (seenHashToKey.containsKey(compositeKey)) {
        duplicateKeysToDelete.add(key);
      } else {
        seenHashToKey[compositeKey] = key.toString();
      }
    }

    for (final dupKey in duplicateKeysToDelete) {
      await _box.delete(dupKey);
    }
  }

  String _cleanFileName(String path) {
    return path.split(RegExp(r'[\\/]')).last.trim();
  }

  /// Appends or updates a cryptographically sealed record in the ledger and triggers cloud sync.
  /// Enforces deduplication by originalFileHash (SHA-256) so sealing the same file multiple times
  /// updates the existing entry in-place rather than generating duplicate entries.
  /// Zero-Trust Guard: If an existing sealed record with the same file name exists but with a different
  /// hash, the original record's hash and C2PA manifest are immutable and preserved.
  Future<void> addRecord(ProvenanceRecord record) async {
    if (!_box.isOpen) {
      throw Exception("Zero-Trust Fault: Unauthorized attempted write to closed ledger.");
    }

    final currentEmail = _supabase?.auth.currentUser?.email?.trim().toLowerCase();
    final effectiveEmail = (record.ownerEmail == null && currentEmail != null && currentEmail.isNotEmpty)
        ? currentEmail
        : record.ownerEmail?.trim().toLowerCase();

    final targetHash = record.originalFileHash.trim().toLowerCase();
    final targetBase = _cleanFileName(record.filePath).toLowerCase();

    // Re-sealing removes any prior tombstone
    _deletedHashes.remove(targetHash);

    // Zero-Trust Guard: Check if a record with the same filename was already sealed by this user.
    // If the file was tampered with (divergent hash), PRESERVE the original sealed record and do not overwrite it!
    final existingByName = getRecordByFileName(targetBase, filterEmail: effectiveEmail);
    if (existingByName != null && existingByName.originalFileHash.trim().toLowerCase() != targetHash) {
      print(">> [LedgerService] Zero-Trust Guard: Tamper attempt detected on '${record.filePath}'. Original SHA-256 seal (${existingByName.originalFileHash}) is immutable and preserved.");
      return;
    }

    // Check for existing records matching this hash and owner email
    final matchingKeys = _box.keys.where((k) {
      final r = _box.get(k);
      if (r == null) return false;
      if (r.id == 'sample-satellite-01' || r.filePath == 'satellite_recon_delta_09.png') return false;
      if (r.originalFileHash.trim().toLowerCase() != targetHash) return false;

      if (effectiveEmail != null && effectiveEmail.isNotEmpty) {
        final rOwner = r.ownerEmail?.trim().toLowerCase();
        return rOwner == null || rOwner == effectiveEmail;
      }
      return true;
    }).toList();

    String targetId = record.id;
    if (matchingKeys.isNotEmpty) {
      // Reuse the first existing record's ID to update in-place
      targetId = matchingKeys.first.toString();
      // If there are any stray duplicates beyond the first, purge them
      for (int i = 1; i < matchingKeys.length; i++) {
        await _box.delete(matchingKeys[i]);
      }
    }

    final recordToSave = record.copyWith(
      id: targetId,
      ownerEmail: effectiveEmail ?? record.ownerEmail,
    );

    await _box.put(targetId, recordToSave);
    notifyListeners();

    // Asynchronously synchronize with authenticated user's cloud account
    if (effectiveEmail != null && effectiveEmail.isNotEmpty && _supabase != null) {
      unawaited(_syncLocalRecordsToCloud(effectiveEmail));
    }
  }

  /// Retrieves a provenance record by its UUID.
  ProvenanceRecord? getRecord(String id) {
    if (!_box.isOpen) {
      throw Exception("Zero-Trust Fault: Unauthorized attempted read from closed ledger.");
    }
    return _box.get(id);
  }

  /// Retrieves a provenance record by its base file name.
  /// Ignores directory prefixes and case. Optionally scopes to a specific owner email.
  ProvenanceRecord? getRecordByFileName(String fileName, {String? filterEmail}) {
    if (!_box.isOpen) return null;
    final targetBase = _cleanFileName(fileName).toLowerCase();
    final targetEmail = (filterEmail ?? _supabase?.auth.currentUser?.email)?.trim().toLowerCase();

    for (final r in _box.values) {
      if (r.id == 'sample-satellite-01' || r.filePath == 'satellite_recon_delta_09.png') continue;
      final recordBase = _cleanFileName(r.filePath).toLowerCase();
      if (recordBase == targetBase) {
        if (targetEmail != null && targetEmail.isNotEmpty) {
          final owner = r.ownerEmail?.trim().toLowerCase();
          if (owner != null && owner != targetEmail) continue;
        }
        return r;
      }
    }
    return null;
  }

  /// Retrieves a provenance record by its SHA-256 file hash.
  /// Optionally scopes to a specific owner email.
  ProvenanceRecord? getRecordByHash(String sha256Hash, {String? filterEmail}) {
    if (!_box.isOpen) return null;
    final targetHash = sha256Hash.trim().toLowerCase();
    final targetEmail = (filterEmail ?? _supabase?.auth.currentUser?.email)?.trim().toLowerCase();

    for (final r in _box.values) {
      if (r.id == 'sample-satellite-01' || r.filePath == 'satellite_recon_delta_09.png') continue;
      if (r.originalFileHash.trim().toLowerCase() == targetHash) {
        if (targetEmail != null && targetEmail.isNotEmpty) {
          final owner = r.ownerEmail?.trim().toLowerCase();
          if (owner != null && owner != targetEmail) continue;
        }
        return r;
      }
    }
    return null;
  }

  /// Retrieves all sealed records in the ledger, excluding sample assets.
  /// Enforces unique representation by file hash so duplicate entries never appear.
  /// Optionally filters by user email so records are cleanly partitioned per account.
  List<ProvenanceRecord> getHistory({String? filterEmail}) {
    if (!_box.isOpen) return [];

    final targetEmail = (filterEmail ?? _supabase?.auth.currentUser?.email)?.trim().toLowerCase();
    final Set<String> seenHashes = {};
    final List<ProvenanceRecord> uniqueRecords = [];

    // Traverse in reverse chronological order (newest first)
    for (final r in _box.values.toList().reversed) {
      // Never display sample or demo assets in the ledger
      if (r.id == 'sample-satellite-01' || r.filePath == 'satellite_recon_delta_09.png') {
        continue;
      }

      final hash = r.originalFileHash.trim().toLowerCase();
      // Zero-Trust: suppress tombstoned or cleared records
      if (_deletedHashes.contains(hash)) {
        continue;
      }
      if (_ledgerClearedAt != null && r.timestamp.toUtc().isBefore(_ledgerClearedAt!)) {
        continue;
      }

      if (targetEmail != null && targetEmail.isNotEmpty) {
        final recordOwner = r.ownerEmail?.trim().toLowerCase();
        // Return records owned by this email, or legacy/offline unassigned records
        final isMatch = recordOwner == null ||
            recordOwner.isEmpty ||
            recordOwner == 'offline@enclave.local' ||
            recordOwner == targetEmail;
        if (!isMatch) {
          continue;
        }
      }

      if (!seenHashes.contains(hash)) {
        seenHashes.add(hash);
        uniqueRecords.add(r);
      }
    }

    return uniqueRecords;
  }

  /// Retrieves the most recently sealed asset for quick P2P transfer.
  ProvenanceRecord? getLatestRecord({String? filterEmail}) {
    final history = getHistory(filterEmail: filterEmail);
    if (history.isEmpty) return null;
    return history.first;
  }

  /// Deletes a single provenance record by its ID or SHA-256 hash.
  /// Stores a distributed tombstone and synchronizes the deletion across all devices logged into the same account.
  Future<bool> deleteRecord(String id) async {
    if (!_box.isOpen) return false;

    ProvenanceRecord? targetRecord;
    dynamic targetKey;

    for (final key in _box.keys) {
      final r = _box.get(key);
      if (r != null && (r.id == id || key.toString() == id || r.originalFileHash.trim().toLowerCase() == id.trim().toLowerCase())) {
        targetRecord = r;
        targetKey = key;
        break;
      }
    }

    if (targetRecord == null && targetKey == null) {
      return false;
    }

    final hash = targetRecord?.originalFileHash.trim().toLowerCase() ?? id.trim().toLowerCase();
    final ownerEmail = targetRecord?.ownerEmail?.trim().toLowerCase() ?? 
        _supabase?.auth.currentUser?.email?.trim().toLowerCase();

    // 1. Remove from local encrypted Hive box
    if (targetKey != null) {
      await _box.delete(targetKey);
    }
    _deletedHashes.add(hash);

    // 2. Sync tombstones & remaining records to cloud metadata
    if (_supabase != null && ownerEmail != null && ownerEmail.isNotEmpty) {
      await _syncLocalRecordsToCloud(ownerEmail);
      await _broadcastDeletion(ownerEmail, hash);
    }

    notifyListeners();
    print(">> [LedgerService] Deleted record '$id' (hash: $hash). Tombstone registered.");
    return true;
  }

  /// Completely wipes ledger history for the current user.
  /// Sets a ledger clear epoch timestamp so all other devices signed into the same email account
  /// will purge their records upon receiving real-time broadcast or during next cloud sync.
  Future<void> clearTotalHistory({String? filterEmail}) async {
    if (!_box.isOpen) return;

    final targetEmail = filterEmail?.trim().toLowerCase() ?? 
        _supabase?.auth.currentUser?.email?.trim().toLowerCase();

    // 1. Purge all records belonging to this user
    final keysToDelete = <dynamic>[];
    for (final key in _box.keys) {
      final r = _box.get(key);
      if (r == null) continue;
      if (targetEmail == null || targetEmail.isEmpty || r.ownerEmail?.trim().toLowerCase() == targetEmail) {
        keysToDelete.add(key);
      }
    }

    for (final k in keysToDelete) {
      await _box.delete(k);
    }

    _deletedHashes.clear();
    _ledgerClearedAt = DateTime.now().toUtc();

    // 2. Synchronize cleared state to Supabase account metadata
    if (_supabase != null && targetEmail != null && targetEmail.isNotEmpty) {
      try {
        await _supabase!.auth.updateUser(
          UserAttributes(data: {
            'sealed_ledger_records': <dynamic>[],
            'deleted_ledger_hashes': <String>[],
            'ledger_cleared_at': _ledgerClearedAt!.toIso8601String(),
          }),
        );
        print(">> [LedgerService] Cloud metadata wiped for $targetEmail (epoch: ${_ledgerClearedAt!.toIso8601String()})");
      } catch (e) {
        print(">> [LedgerService] Notice: Error updating cloud metadata during total clear: $e");
      }
      await _broadcastClearTotal(targetEmail, _ledgerClearedAt!);
    }

    notifyListeners();
  }

  /// Helper to obtain this client's unique node device ID
  String _getDeviceId() {
    try {
      if (Hive.isBoxOpen('kerberos_device_identity')) {
        final box = Hive.box('kerberos_device_identity');
        final stored = box.get('device_uuid')?.toString();
        if (stored != null && stored.trim().isNotEmpty) {
          return stored.trim();
        }
      }
    } catch (_) {}
    return _localDeviceId;
  }

  /// Subscribes to a Supabase Realtime broadcast channel dedicated to cross-device ledger sync.
  void initRealtimeSync(String email) {
    // Zero-Trust Guard: Realtime sync explicitly disabled to enforce air-gapped ledger constraint.
    return;
  }

  Future<void> _broadcastDeletion(String email, String hash) async {
    // Zero-Trust Guard: Realtime sync explicitly disabled to enforce air-gapped ledger constraint.
    return;
  }

  Future<void> _broadcastClearTotal(String email, DateTime clearedAt) async {
    // Zero-Trust Guard: Realtime sync explicitly disabled to enforce air-gapped ledger constraint.
    return;
  }

  /// Synchronizes ledger records between local Hive storage and Supabase user metadata.
  Future<void> syncWithUserAccount(User user) async {
    // Zero-Trust Guard: Cloud sync explicitly disabled to enforce air-gapped ledger constraint.
    return;
  }

  /// Core cross-computer cloud synchronization with tombstone reconciliation.
  Future<void> syncWithCloud(String userEmail, {Map<String, dynamic>? userMeta}) async {
    // Zero-Trust Guard: Cloud sync explicitly disabled to enforce air-gapped ledger constraint.
    return;
  }

  /// Uploads the current user's sealed records and active tombstones to their Supabase account metadata.
  Future<void> _syncLocalRecordsToCloud(String email) async {
    // Zero-Trust Guard: Cloud sync explicitly disabled to enforce air-gapped ledger constraint.
    return;
  }

  /// Explicitly locks down the ledger, flushing all memory buffers.
  Future<void> lock() async {
    if (_box.isOpen) {
      await _box.close();
    }
  }
}

