import 'dart:async';
import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:uuid/uuid.dart';
import '../models/provenance_record.dart';

/// Zero-Trust local ledger.
/// Operates locally using AES-256 encryption via HiveCipher.
/// Provides seamless cross-computer cloud synchronization bound to the authenticated email.
class LedgerService extends ChangeNotifier {
  static const String _boxName = 'secure_provenance_ledger';
  late Box<ProvenanceRecord> _box;
  SupabaseClient? _supabase;

  // Distributed tombstone & sync state
  final Set<String> _deletedHashes = {};
  DateTime? _ledgerClearedAt;
  RealtimeChannel? _realtimeSyncChannel;
  String? _currentSubscribedEmail;
  final String _localDeviceId = const Uuid().v4();

  LedgerService({SupabaseClient? supabaseClient}) : _supabase = supabaseClient;

  void setSupabaseClient(SupabaseClient client) {
    _supabase = client;
  }

  /// Initializes the air-gapped AES-256 encrypted ledger.
  /// Purges any legacy sample/mock assets to ensure an authentic clean state.
  Future<void> initialize() async {
    await Hive.initFlutter();
    
    // Register adapter generated by hive_generator
    if (!Hive.isAdapterRegistered(0)) {
      Hive.registerAdapter(ProvenanceRecordAdapter());
    }

    // Retrieve AES-256 key from secure environment variable layer
    final base64Key = dotenv.env['HIVE_ENCRYPTION_KEY_BASE64'];
    if (base64Key == null || base64Key.isEmpty) {
      throw Exception("Zero-Trust Fault: Ledger encryption key not found. System halting to protect data.");
    }

    final encryptionKey = base64Decode(base64Key);
    if (encryptionKey.length != 32) {
      throw Exception("Zero-Trust Fault: Invalid AES-256 key length detected.");
    }

    // Initialize exclusively with the strict AES-256 cipher
    _box = await Hive.openBox<ProvenanceRecord>(
      _boxName,
      encryptionCipher: HiveAesCipher(encryptionKey),
    );

    // ZERO-TRUST PURGE: Clear the current ledger state/mock data to remove 
    // any ingested .m4a files and legacy cloud-synced test data.
    await _box.clear();

    // PURGE SAMPLE ASSETS: Ensure demo/sample assets are never retained in persistent storage
    final sampleKeys = _box.keys.where((k) {
      final rec = _box.get(k);
      if (k == 'sample-satellite-01' ||
          rec?.id == 'sample-satellite-01' ||
          rec?.filePath == 'satellite_recon_delta_09.png') {
        return true;
      }
      // Zero-Trust Guard: Strictly reject and purge any audio mock data (prevent voice-spoofing)
      if (rec?.filePath.toLowerCase().endsWith('.m4a') == true) {
        return true;
      }
      return false;
    }).toList();

    for (final k in sampleKeys) {
      await _box.delete(k);
    }

    // DEDUPLICATE RECORDS: Purge any legacy duplicate records with identical hash & owner
    final Map<String, String> seenHashToKey = {};
    final List<dynamic> duplicateKeysToDelete = [];

    for (final key in _box.keys) {
      final rec = _box.get(key);
      if (rec == null) continue;
      if (rec.id == 'sample-satellite-01' || rec.filePath == 'satellite_recon_delta_09.png') continue;

      final hash = rec.originalFileHash.trim().toLowerCase();
      final owner = rec.ownerEmail?.trim().toLowerCase() ?? '';
      final compositeKey = '$owner::$hash';

      if (seenHashToKey.containsKey(compositeKey)) {
        duplicateKeysToDelete.add(key);
      } else {
        seenHashToKey[compositeKey] = key.toString();
      }
    }

    for (final dupKey in duplicateKeysToDelete) {
      await _box.delete(dupKey);
    }
  }

  String _cleanFileName(String path) {
    return path.split(RegExp(r'[\\/]')).last.trim();
  }

  /// Appends or updates a cryptographically sealed record in the ledger and triggers cloud sync.
  /// Enforces deduplication by originalFileHash (SHA-256) so sealing the same file multiple times
  /// updates the existing entry in-place rather than generating duplicate entries.
  /// Zero-Trust Guard: If an existing sealed record with the same file name exists but with a different
  /// hash, the original record's hash and C2PA manifest are immutable and preserved.
  Future<void> addRecord(ProvenanceRecord record) async {
    if (!_box.isOpen) {
      throw Exception("Zero-Trust Fault: Unauthorized attempted write to closed ledger.");
    }

    final currentEmail = _supabase?.auth.currentUser?.email?.trim().toLowerCase();
    final effectiveEmail = (record.ownerEmail == null && currentEmail != null && currentEmail.isNotEmpty)
        ? currentEmail
        : record.ownerEmail?.trim().toLowerCase();

    final targetHash = record.originalFileHash.trim().toLowerCase();
    final targetBase = _cleanFileName(record.filePath).toLowerCase();

    // Re-sealing removes any prior tombstone
    _deletedHashes.remove(targetHash);

    // Zero-Trust Guard: Check if a record with the same filename was already sealed by this user.
    // If the file was tampered with (divergent hash), PRESERVE the original sealed record and do not overwrite it!
    final existingByName = getRecordByFileName(targetBase, filterEmail: effectiveEmail);
    if (existingByName != null && existingByName.originalFileHash.trim().toLowerCase() != targetHash) {
      print(">> [LedgerService] Zero-Trust Guard: Tamper attempt detected on '${record.filePath}'. Original SHA-256 seal (${existingByName.originalFileHash}) is immutable and preserved.");
      return;
    }

    // Check for existing records matching this hash and owner email
    final matchingKeys = _box.keys.where((k) {
      final r = _box.get(k);
      if (r == null) return false;
      if (r.id == 'sample-satellite-01' || r.filePath == 'satellite_recon_delta_09.png') return false;
      if (r.originalFileHash.trim().toLowerCase() != targetHash) return false;

      if (effectiveEmail != null && effectiveEmail.isNotEmpty) {
        final rOwner = r.ownerEmail?.trim().toLowerCase();
        return rOwner == null || rOwner == effectiveEmail;
      }
      return true;
    }).toList();

    String targetId = record.id;
    if (matchingKeys.isNotEmpty) {
      // Reuse the first existing record's ID to update in-place
      targetId = matchingKeys.first.toString();
      // If there are any stray duplicates beyond the first, purge them
      for (int i = 1; i < matchingKeys.length; i++) {
        await _box.delete(matchingKeys[i]);
      }
    }

    final recordToSave = record.copyWith(
      id: targetId,
      ownerEmail: effectiveEmail ?? record.ownerEmail,
    );

    await _box.put(targetId, recordToSave);
    notifyListeners();

    // Asynchronously synchronize with authenticated user's cloud account
    if (effectiveEmail != null && effectiveEmail.isNotEmpty && _supabase != null) {
      unawaited(_syncLocalRecordsToCloud(effectiveEmail));
    }
  }

  /// Retrieves a provenance record by its UUID.
  ProvenanceRecord? getRecord(String id) {
    if (!_box.isOpen) {
      throw Exception("Zero-Trust Fault: Unauthorized attempted read from closed ledger.");
    }
    return _box.get(id);
  }

  /// Retrieves a provenance record by its base file name.
  /// Ignores directory prefixes and case. Optionally scopes to a specific owner email.
  ProvenanceRecord? getRecordByFileName(String fileName, {String? filterEmail}) {
    if (!_box.isOpen) return null;
    final targetBase = _cleanFileName(fileName).toLowerCase();
    final targetEmail = (filterEmail ?? _supabase?.auth.currentUser?.email)?.trim().toLowerCase();

    for (final r in _box.values) {
      if (r.id == 'sample-satellite-01' || r.filePath == 'satellite_recon_delta_09.png') continue;
      final recordBase = _cleanFileName(r.filePath).toLowerCase();
      if (recordBase == targetBase) {
        if (targetEmail != null && targetEmail.isNotEmpty) {
          final owner = r.ownerEmail?.trim().toLowerCase();
          if (owner != null && owner != targetEmail) continue;
        }
        return r;
      }
    }
    return null;
  }

  /// Retrieves a provenance record by its SHA-256 file hash.
  /// Optionally scopes to a specific owner email.
  ProvenanceRecord? getRecordByHash(String sha256Hash, {String? filterEmail}) {
    if (!_box.isOpen) return null;
    final targetHash = sha256Hash.trim().toLowerCase();
    final targetEmail = (filterEmail ?? _supabase?.auth.currentUser?.email)?.trim().toLowerCase();

    for (final r in _box.values) {
      if (r.id == 'sample-satellite-01' || r.filePath == 'satellite_recon_delta_09.png') continue;
      if (r.originalFileHash.trim().toLowerCase() == targetHash) {
        if (targetEmail != null && targetEmail.isNotEmpty) {
          final owner = r.ownerEmail?.trim().toLowerCase();
          if (owner != null && owner != targetEmail) continue;
        }
        return r;
      }
    }
    return null;
  }

  /// Retrieves all sealed records in the ledger, excluding sample assets.
  /// Enforces unique representation by file hash so duplicate entries never appear.
  /// Optionally filters by user email so records are cleanly partitioned per account.
  List<ProvenanceRecord> getHistory({String? filterEmail}) {
    if (!_box.isOpen) return [];

    final targetEmail = (filterEmail ?? _supabase?.auth.currentUser?.email)?.trim().toLowerCase();
    final Set<String> seenHashes = {};
    final List<ProvenanceRecord> uniqueRecords = [];

    // Traverse in reverse chronological order (newest first)
    for (final r in _box.values.toList().reversed) {
      // Never display sample or demo assets in the ledger
      if (r.id == 'sample-satellite-01' || r.filePath == 'satellite_recon_delta_09.png') {
        continue;
      }

      final hash = r.originalFileHash.trim().toLowerCase();
      // Zero-Trust: suppress tombstoned or cleared records
      if (_deletedHashes.contains(hash)) {
        continue;
      }
      if (_ledgerClearedAt != null && r.timestamp.toUtc().isBefore(_ledgerClearedAt!)) {
        continue;
      }

      if (targetEmail != null && targetEmail.isNotEmpty) {
        final recordOwner = r.ownerEmail?.trim().toLowerCase();
        // Return records owned by this email, or legacy/offline unassigned records
        final isMatch = recordOwner == null ||
            recordOwner.isEmpty ||
            recordOwner == 'offline@enclave.local' ||
            recordOwner == targetEmail;
        if (!isMatch) {
          continue;
        }
      }

      if (!seenHashes.contains(hash)) {
        seenHashes.add(hash);
        uniqueRecords.add(r);
      }
    }

    return uniqueRecords;
  }

  /// Retrieves the most recently sealed asset for quick P2P transfer.
  ProvenanceRecord? getLatestRecord({String? filterEmail}) {
    final history = getHistory(filterEmail: filterEmail);
    if (history.isEmpty) return null;
    return history.first;
  }

  /// Deletes a single provenance record by its ID or SHA-256 hash.
  /// Stores a distributed tombstone and synchronizes the deletion across all devices logged into the same account.
  Future<bool> deleteRecord(String id) async {
    if (!_box.isOpen) return false;

    ProvenanceRecord? targetRecord;
    dynamic targetKey;

    for (final key in _box.keys) {
      final r = _box.get(key);
      if (r != null && (r.id == id || key.toString() == id || r.originalFileHash.trim().toLowerCase() == id.trim().toLowerCase())) {
        targetRecord = r;
        targetKey = key;
        break;
      }
    }

    if (targetRecord == null && targetKey == null) {
      return false;
    }

    final hash = targetRecord?.originalFileHash.trim().toLowerCase() ?? id.trim().toLowerCase();
    final ownerEmail = targetRecord?.ownerEmail?.trim().toLowerCase() ?? 
        _supabase?.auth.currentUser?.email?.trim().toLowerCase();

    // 1. Remove from local encrypted Hive box
    if (targetKey != null) {
      await _box.delete(targetKey);
    }
    _deletedHashes.add(hash);

    // 2. Sync tombstones & remaining records to cloud metadata
    if (_supabase != null && ownerEmail != null && ownerEmail.isNotEmpty) {
      await _syncLocalRecordsToCloud(ownerEmail);
      await _broadcastDeletion(ownerEmail, hash);
    }

    notifyListeners();
    print(">> [LedgerService] Deleted record '$id' (hash: $hash). Tombstone registered.");
    return true;
  }

  /// Completely wipes ledger history for the current user.
  /// Sets a ledger clear epoch timestamp so all other devices signed into the same email account
  /// will purge their records upon receiving real-time broadcast or during next cloud sync.
  Future<void> clearTotalHistory({String? filterEmail}) async {
    if (!_box.isOpen) return;

    final targetEmail = filterEmail?.trim().toLowerCase() ?? 
        _supabase?.auth.currentUser?.email?.trim().toLowerCase();

    // 1. Purge all records belonging to this user
    final keysToDelete = <dynamic>[];
    for (final key in _box.keys) {
      final r = _box.get(key);
      if (r == null) continue;
      if (targetEmail == null || targetEmail.isEmpty || r.ownerEmail?.trim().toLowerCase() == targetEmail) {
        keysToDelete.add(key);
      }
    }

    for (final k in keysToDelete) {
      await _box.delete(k);
    }

    _deletedHashes.clear();
    _ledgerClearedAt = DateTime.now().toUtc();

    // 2. Synchronize cleared state to Supabase account metadata
    if (_supabase != null && targetEmail != null && targetEmail.isNotEmpty) {
      try {
        await _supabase!.auth.updateUser(
          UserAttributes(data: {
            'sealed_ledger_records': <dynamic>[],
            'deleted_ledger_hashes': <String>[],
            'ledger_cleared_at': _ledgerClearedAt!.toIso8601String(),
          }),
        );
        print(">> [LedgerService] Cloud metadata wiped for $targetEmail (epoch: ${_ledgerClearedAt!.toIso8601String()})");
      } catch (e) {
        print(">> [LedgerService] Notice: Error updating cloud metadata during total clear: $e");
      }
      await _broadcastClearTotal(targetEmail, _ledgerClearedAt!);
    }

    notifyListeners();
  }

  /// Helper to obtain this client's unique node device ID
  String _getDeviceId() {
    try {
      if (Hive.isBoxOpen('kerberos_device_identity')) {
        final box = Hive.box('kerberos_device_identity');
        final stored = box.get('device_uuid')?.toString();
        if (stored != null && stored.trim().isNotEmpty) {
          return stored.trim();
        }
      }
    } catch (_) {}
    return _localDeviceId;
  }

  /// Subscribes to a Supabase Realtime broadcast channel dedicated to cross-device ledger sync.
  void initRealtimeSync(String email) {
    if (_supabase == null) return;
    final cleanEmail = email.trim().toLowerCase();
    if (cleanEmail.isEmpty) return;

    if (_currentSubscribedEmail == cleanEmail && _realtimeSyncChannel != null) {
      return;
    }

    try {
      _currentSubscribedEmail = cleanEmail;
      final channelName = 'ledger-sync:$cleanEmail';
      _realtimeSyncChannel = _supabase!.channel(channelName);

      _realtimeSyncChannel!
          .onBroadcast(
            event: 'delete_single',
            callback: (payload) async {
              final sender = payload['sender_device_id']?.toString();
              if (sender == _getDeviceId()) return;
              final targetHash = payload['hash']?.toString().trim().toLowerCase();
              if (targetHash != null && targetHash.isNotEmpty) {
                _deletedHashes.add(targetHash);
                final keysToPurge = <dynamic>[];
                for (final k in _box.keys) {
                  final r = _box.get(k);
                  if (r != null && r.originalFileHash.trim().toLowerCase() == targetHash) {
                    keysToPurge.add(k);
                  }
                }
                for (final k in keysToPurge) {
                  await _box.delete(k);
                }
                notifyListeners();
                print(">> [LedgerService] Realtime sync: Purged deleted hash '$targetHash' from peer broadcast.");
              }
            },
          )
          .onBroadcast(
            event: 'clear_total',
            callback: (payload) async {
              final sender = payload['sender_device_id']?.toString();
              if (sender == _getDeviceId()) return;
              final clearedAtStr = payload['cleared_at']?.toString();
              if (clearedAtStr != null) {
                final clearedAt = DateTime.tryParse(clearedAtStr)?.toUtc();
                if (clearedAt != null) {
                  _ledgerClearedAt = clearedAt;
                  final keysToPurge = <dynamic>[];
                  for (final k in _box.keys) {
                    final r = _box.get(k);
                    if (r != null && r.timestamp.toUtc().isBefore(clearedAt)) {
                      keysToPurge.add(k);
                    }
                  }
                  for (final k in keysToPurge) {
                    await _box.delete(k);
                  }
                  _deletedHashes.clear();
                  notifyListeners();
                  print(">> [LedgerService] Realtime sync: Cleared total history older than $clearedAt from peer broadcast.");
                }
              }
            },
          )
          .subscribe();
    } catch (e) {
      print(">> [LedgerService] Realtime subscription notice: $e");
    }
  }

  Future<void> _broadcastDeletion(String email, String hash) async {
    if (_supabase == null || _realtimeSyncChannel == null) return;
    try {
      await _realtimeSyncChannel!.sendBroadcastMessage(
        event: 'delete_single',
        payload: {
          'sender_device_id': _getDeviceId(),
          'hash': hash,
          'email': email,
          'timestamp': DateTime.now().toUtc().toIso8601String(),
        },
      );
    } catch (e) {
      print(">> [LedgerService] Realtime broadcast notice: $e");
    }
  }

  Future<void> _broadcastClearTotal(String email, DateTime clearedAt) async {
    if (_supabase == null || _realtimeSyncChannel == null) return;
    try {
      await _realtimeSyncChannel!.sendBroadcastMessage(
        event: 'clear_total',
        payload: {
          'sender_device_id': _getDeviceId(),
          'cleared_at': clearedAt.toIso8601String(),
          'email': email,
        },
      );
    } catch (e) {
      print(">> [LedgerService] Realtime broadcast notice: $e");
    }
  }

  /// Synchronizes ledger records between local Hive storage and Supabase user metadata.
  Future<void> syncWithUserAccount(User user) async {
    if (!_box.isOpen) return;
    final userEmail = user.email?.trim().toLowerCase();
    if (userEmail == null || userEmail.isEmpty) return;

    await syncWithCloud(userEmail, userMeta: user.userMetadata);
  }

  /// Core cross-computer cloud synchronization with Zero-Trust Ingest Verification Gate.
  /// Protects against cloud ledger poisoning, corrupted JSON, zombie resurrections, and tampering.
  Future<void> syncWithCloud(String userEmail, {Map<String, dynamic>? userMeta}) async {
    if (!_box.isOpen) return;
    final cleanEmail = userEmail.trim().toLowerCase();
    if (cleanEmail.isEmpty) return;

    // Activate real-time mesh subscription for instant cross-machine notification
    initRealtimeSync(cleanEmail);

    Map<String, dynamic>? meta = userMeta;
    if (meta == null && _supabase != null) {
      try {
        final userResponse = await _supabase!.auth.getUser();
        meta = userResponse.user?.userMetadata ?? _supabase!.auth.currentUser?.userMetadata;
      } catch (_) {
        meta = _supabase!.auth.currentUser?.userMetadata;
      }
    } else {
      meta ??= _supabase?.auth.currentUser?.userMetadata;
    }
    bool localModified = false;

    // 1. Reconcile total history wipe epoch
    final cloudClearedAtStr = meta?['ledger_cleared_at']?.toString();
    if (cloudClearedAtStr != null) {
      final cloudClearedAt = DateTime.tryParse(cloudClearedAtStr)?.toUtc();
      if (cloudClearedAt != null) {
        if (_ledgerClearedAt == null || cloudClearedAt.isAfter(_ledgerClearedAt!)) {
          _ledgerClearedAt = cloudClearedAt;
          final keysToPurge = <dynamic>[];
          for (final k in _box.keys) {
            final r = _box.get(k);
            if (r != null && r.timestamp.toUtc().isBefore(cloudClearedAt)) {
              keysToPurge.add(k);
            }
          }
          for (final k in keysToPurge) {
            await _box.delete(k);
            localModified = true;
          }
        }
      }
    }

    // 2. Reconcile remote tombstones (deleted hashes)
    final remoteTombstones = meta?['deleted_ledger_hashes'];
    if (remoteTombstones is List) {
      for (final h in remoteTombstones) {
        if (h != null) {
          _deletedHashes.add(h.toString().trim().toLowerCase());
        }
      }
    }

    // Purge local records matching tombstoned hashes (prevents zombie resurrection)
    final zombieKeys = <dynamic>[];
    for (final k in _box.keys) {
      final r = _box.get(k);
      if (r != null && _deletedHashes.contains(r.originalFileHash.trim().toLowerCase())) {
        zombieKeys.add(k);
      }
    }
    for (final k in zombieKeys) {
      await _box.delete(k);
      localModified = true;
    }

    // 3. Reconcile remote sealed records with Zero-Trust Anti-Poisoning Gate
    final remoteRaw = meta?['sealed_ledger_records'];
    final Set<String> knownIds = {};
    final Set<String> knownHashes = {};
    bool hasNewLocalForCloud = false;

    if (remoteRaw is List) {
      for (final item in remoteRaw) {
        if (item is Map) {
          try {
            final record = ProvenanceRecord.fromJson(Map<String, dynamic>.from(item));
            if (record.id.isNotEmpty && record.id != 'sample-satellite-01' && record.filePath != 'satellite_recon_delta_09.png') {
              final hash = record.originalFileHash.trim().toLowerCase();

              // Zero-Trust Guard: Ignore tombstoned or cleared records
              if (_deletedHashes.contains(hash)) continue;
              if (_ledgerClearedAt != null && record.timestamp.toUtc().isBefore(_ledgerClearedAt!)) continue;

              // Zero-Trust Guard: Validate cryptographic hash format (minimum 16 alphanumeric characters)
              if (hash.length < 16 || RegExp(r'[^a-fA-F0-9]').hasMatch(hash)) {
                print(">> [LedgerService] Zero-Trust Guard: Rejected corrupted/malformed hash in cloud record: '$hash'");
                continue;
              }

              // Zero-Trust Guard: Anti-Poisoning & Anti-Splicing Check
              // Check if a local verified record exists with the same filename.
              // If the cloud provides a divergent hash for that file, the cloud is POISONED or TAMPERED.
              // We strictly REJECT and QUARANTINE the cloud record, preserving our local verified seal!
              final cleanBase = _cleanFileName(record.filePath).toLowerCase();
              final existingLocalByName = getRecordByFileName(cleanBase, filterEmail: cleanEmail);
              if (existingLocalByName != null && existingLocalByName.originalFileHash.trim().toLowerCase() != hash) {
                print(">> [LedgerService] Zero-Trust Guard: Cloud tampering/poisoning attempt detected on '$cleanBase'. Cloud hash ($hash) diverges from local verified baseline (${existingLocalByName.originalFileHash}). Cloud record rejected and quarantined.");
                hasNewLocalForCloud = true; // Trigger authoritative repair: overwrite cloud with clean local baseline!
                continue; // Strictly reject poisoned cloud entry
              }

              if (knownHashes.contains(hash)) continue;
              knownHashes.add(hash);
              knownIds.add(record.id);

              final existingById = _box.get(record.id);
              final existingByHash = _box.values.cast<ProvenanceRecord?>().firstWhere(
                (r) => r != null && r.originalFileHash.trim().toLowerCase() == hash,
                orElse: () => null,
              );

              if (existingById != null) {
                if (existingById.ownerEmail == null && record.ownerEmail != null) {
                  await _box.put(record.id, existingById.copyWith(ownerEmail: record.ownerEmail));
                  localModified = true;
                }
              } else if (existingByHash != null) {
                if (existingByHash.ownerEmail == null && record.ownerEmail != null) {
                  await _box.put(existingByHash.id, existingByHash.copyWith(ownerEmail: record.ownerEmail));
                  localModified = true;
                }
              } else {
                await _box.put(record.id, record);
                localModified = true;
              }
            }
          } catch (e) {
            print(">> [LedgerService] Notice: Error restoring remote record: $e");
          }
        }
      }
    }

    // 4. Reconcile local records owned by this user (or unowned) that are not yet in cloud
    final localRecords = _box.values.where((r) {
      return r.id != 'sample-satellite-01' && r.filePath != 'satellite_recon_delta_09.png';
    }).toList();

    for (final r in localRecords) {
      final owner = r.ownerEmail?.trim().toLowerCase();
      final hash = r.originalFileHash.trim().toLowerCase();
      if (_deletedHashes.contains(hash)) continue;

      if (owner == null) {
        final updated = r.copyWith(ownerEmail: cleanEmail);
        await _box.put(r.id, updated);
        hasNewLocalForCloud = true;
        localModified = true;
      } else if (owner == cleanEmail && !knownHashes.contains(hash)) {
        hasNewLocalForCloud = true;
      }
    }

    // 5. Authoritative Self-Healing: Push reconciled state to heal cloud if local storage had new/authoritative assets
    if (hasNewLocalForCloud && _supabase != null) {
      await _syncLocalRecordsToCloud(cleanEmail);
    }

    if (localModified) {
      notifyListeners();
    }
  }

  /// Uploads the current user's sealed records and active tombstones to their Supabase account metadata.
  Future<void> _syncLocalRecordsToCloud(String email) async {
    if (_supabase == null || !_box.isOpen) return;
    final cleanEmail = email.trim().toLowerCase();
    if (cleanEmail.isEmpty) return;

    try {
      final Map<String, ProvenanceRecord> uniqueRecordsByHash = {};
      for (final r in _box.values) {
        if (r.id == 'sample-satellite-01' || r.filePath == 'satellite_recon_delta_09.png') continue;
        final hash = r.originalFileHash.trim().toLowerCase();
        if (_deletedHashes.contains(hash)) continue;

        final owner = r.ownerEmail?.trim().toLowerCase();
        if (owner == null || owner == cleanEmail) {
          uniqueRecordsByHash[hash] = r.copyWith(ownerEmail: cleanEmail);
        }
      }

      final recordsJson = uniqueRecordsByHash.values.map((r) => r.toJson()).toList();

      await _supabase!.auth.updateUser(
        UserAttributes(data: {
          'sealed_ledger_records': recordsJson,
          'deleted_ledger_hashes': _deletedHashes.toList(),
          if (_ledgerClearedAt != null) 'ledger_cleared_at': _ledgerClearedAt!.toIso8601String(),
        }),
      );
      print(">> [LedgerService] Cloud sync successful: ${recordsJson.length} sealed records, ${_deletedHashes.length} tombstones bound to $cleanEmail");
    } catch (e) {
      print(">> [LedgerService] Cloud sync notice (offline or transient): $e");
    }
  }

  /// Performs an in-memory Zero-Trust cryptographic audit of all local ledger records.
  /// Detects corrupt hashes, unverified entries, zombie tombstones, and multi-version hash divergences.
  LedgerAuditReport auditLedgerIntegrity({String? filterEmail}) {
    if (!_box.isOpen) {
      return const LedgerAuditReport(
        totalRecords: 0,
        verifiedRecords: 0,
        quarantinedRecords: 0,
        isIntegrityIntact: false,
        anomalyDescriptions: ['Zero-Trust Fault: Ledger box is closed or locked.'],
      );
    }

    final targetEmail = (filterEmail ?? _supabase?.auth.currentUser?.email)?.trim().toLowerCase();
    final records = _box.values.where((r) {
      if (r.id == 'sample-satellite-01' || r.filePath == 'satellite_recon_delta_09.png') return false;
      if (targetEmail != null && targetEmail.isNotEmpty) {
        final owner = r.ownerEmail?.trim().toLowerCase();
        return owner == null || owner.isEmpty || owner == 'offline@enclave.local' || owner == targetEmail;
      }
      return true;
    }).toList();

    int verified = 0;
    int quarantined = 0;
    final List<String> anomalies = [];
    final Map<String, String> fileNameToHash = {};

    for (final r in records) {
      final hash = r.originalFileHash.trim().toLowerCase();
      final base = _cleanFileName(r.filePath).toLowerCase();

      // Check 1: Tombstone violation (zombie presence)
      if (_deletedHashes.contains(hash)) {
        quarantined++;
        anomalies.add("Zombie record detected: '${r.filePath}' exists locally despite registered tombstone ($hash).");
        continue;
      }

      // Check 2: Hash format integrity (must be alphanumeric hex >= 16 chars)
      if (hash.isEmpty || hash.length < 16 || RegExp(r'[^a-fA-F0-9]').hasMatch(hash)) {
        quarantined++;
        anomalies.add("Cryptographic hash corrupt on '${r.filePath}': invalid hex format '$hash'.");
        continue;
      }

      // Check 3: Unique filename hash divergence
      if (fileNameToHash.containsKey(base)) {
        final prevHash = fileNameToHash[base]!;
        if (prevHash != hash) {
          quarantined++;
          anomalies.add("Hash divergence on identical file '$base': '$prevHash' vs '$hash'.");
          continue;
        }
      } else {
        fileNameToHash[base] = hash;
      }

      // Check 4: Signature presence
      if (r.signature.isEmpty) {
        quarantined++;
        anomalies.add("Unsigned provenance record detected on '${r.filePath}'.");
        continue;
      }

      verified++;
    }

    return LedgerAuditReport(
      totalRecords: records.length,
      verifiedRecords: verified,
      quarantinedRecords: quarantined,
      isIntegrityIntact: quarantined == 0,
      anomalyDescriptions: anomalies,
    );
  }

  /// Explicitly locks down the ledger, flushing all memory buffers.
  Future<void> lock() async {
    if (_box.isOpen) {
      await _box.close();
    }
  }
}

/// Structured Zero-Trust audit report summarizing cryptographic ledger health.
class LedgerAuditReport {
  final int totalRecords;
  final int verifiedRecords;
  final int quarantinedRecords;
  final bool isIntegrityIntact;
  final List<String> anomalyDescriptions;

  const LedgerAuditReport({
    required this.totalRecords,
    required this.verifiedRecords,
    required this.quarantinedRecords,
    required this.isIntegrityIntact,
    required this.anomalyDescriptions,
  });
}

